version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  dashboard:
    build: ./dashboard
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - server
      - db

  server:
    build: ./server
    command: flask run -h 0.0.0.0 -p 3333
    # environment:
    #   - DATABASE_URL=postgresql://myuser:mypassword@db:5432/db
    ports:
      - "3333:3333"
    depends_on:
      - db